### ISSUE TITLE
A troll miner can forbid transaction from ever being accepted.

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/Scorex#120]
Right now for a payment transaction to be accepted, it must be the newest transaction in the account.
This is a source of problems when there is > 1 outgoing transaction from an account at the same time.

It's easy to imagine a scenario:
- Asset Issuer pays a dividend. It consists of a 100 transactions.
- The Troll Miner has the right to the next block.
- The Troll Miner accepts only the newest transaction into the block.

In this case StoredState.scala will deny any of the remaining 99 transactions from ever being accepted into the block, forcing the Asset Issuer to resend the dividend [but only to the remaining 99 people... lots of hassle].

Thus, I think that "only the newest transaction is accepted" is a bad idea and should be scrapped. We already have an allowance of `MaxTxAndBlockDiff = 2.hour`. I think that this is enough.

_Should this change be implemented, it's important to add a check if the transaction with the same ID is in the database, as currently there are no such checks in code._

**Comment by alexeykiselev** [comment]
This scenario is possible and was considered the lesser evil.

**Comment by bcdev-** [comment]
I'm unable to think of any advantage of current approach.
What are the advantages of current approach when compared to `respect MaxTxAndBlockDiff & ignore duplicate transactions`?
