### ISSUE TITLE
Sending WAVES for free

### ISSUE THREAD

**Issue by ghost** [wavesplatform/Scorex#155]
With current setup I can send coins for free. It is possible to pay for waves transfer with issued assets. So for 1 WAVE I can create 100kk asset tokens and then pay with them for WAVES transfer.

Example POST /assets/transfer request:

`{
  "recipient": "3N3wZj2fg7Ue3EVpL49rdG6LF3M77mjrSt7",
  "assetIdOpt": null,
  "feeAsset": "31yDx5PgDccxDv8T21h8A5H3yTfuK4VKYezq7n5McTYa",
  "feeAmount": 1,
  "amount": 1,
  "attachment": "shto",
  "sender": "3NB5VV6gpfGDUrBd4TaofsmzDv5U3atxUjf"
}`

Response:

`{
  "type": 4,
  "id": "F3pJ3f9N64yLVKAUaaKoYqtDmT1K5Mn2caapGNDSGMAq",
  "sender": "3NB5VV6gpfGDUrBd4TaofsmzDv5U3atxUjf",
  "senderPublicKey": "8FSaLWagECb7BiXFxkPgpTjyf6hHSKgpGCBfz3WacLvA",
  "recipient": "3N3wZj2fg7Ue3EVpL49rdG6LF3M77mjrSt7",
  "assetId": null,
  "amount": 1,
  "feeAsset": "31yDx5PgDccxDv8T21h8A5H3yTfuK4VKYezq7n5McTYa",
  "fee": 1,
  "timestamp": 1477316669125,
  "attachment": "shto",
  "signature": "5D1taUNXC84x2FNao5h394UiMESvC1RjgCnHMnusP4rGwsrHctsBYuPudPjkvcC1Pmze6TuiLh3jnT2fYJQjD7qq"
}`

Transaction: [http://testnet.wavesexplorer.com/tx/F3pJ3f9N64yLVKAUaaKoYqtDmT1K5Mn2caapGNDSGMAq](http://testnet.wavesexplorer.com/tx/F3pJ3f9N64yLVKAUaaKoYqtDmT1K5Mn2caapGNDSGMAq)

**Comment by B83YPoj** [comment]
By default miners don't accept transactions with fee in assets, they should explicitly add asset they will accept as fee to whitelist https://github.com/wavesplatform/Scorex/commit/351b5ad3fe4f0d7039694c8de67cf780eee3e4b1

**Comment by bcdev-** [comment]
My proposed solution is this: "Every time someone tries to pay a fee in anything other than Waves, a market order is executed to cover the fees." - https://github.com/wavesplatform/Scorex/issues/132
However, this can wait - WhiteList is enough for now, we can implement this change in a hard fork.
