### ISSUE TITLE
Transfer of asset which is not exist

### ISSUE THREAD

**Issue by ghost** [wavesplatform/Scorex#157]
[http://52.28.66.217:6869/blocks/at/186708](http://52.28.66.217:6869/blocks/at/186708) this block contains transfers of asset with ID F7LSFLL2q9hhfrUfJzZ7rGah5L6mZhHuteLPR49Ze5Lo and this asset is not exist on the blockchain.

[http://52.28.66.217:6869/transactions/info/F7LSFLL2q9hhfrUfJzZ7rGah5L6mZhHuteLPR49Ze5Lo](http://52.28.66.217:6869/transactions/info/F7LSFLL2q9hhfrUfJzZ7rGah5L6mZhHuteLPR49Ze5Lo)

**Comment by bcdev-** [comment]
I confirm. Something fishy is going on.
@B83YPoj Could you take a look what's going on here?

**Comment by Tolsi** [comment]
Do you save the results to json? Links are short-lived, we can not check anything now

**Comment by bcdev-** [comment]
Well, after the network hard-fork diagnosing this bug is almost impossible. :-/
